import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";

export async function POST(request: NextRequest) {
    const session = await auth();
    if (!session?.isAdmin) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    try {
        const body = await request.json();
        const { targetLang, targetLangName, keysToTranslate, referenceTranslations } = body;

        if (!targetLang || !keysToTranslate || !referenceTranslations || !Array.isArray(keysToTranslate)) {
            return NextResponse.json({ error: "Missing required parameters" }, { status: 400 });
        }

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ error: "GEMINI_API_KEY is not configured in .env" }, { status: 500 });
        }

        // Construct a prompt for Gemini
        const systemPrompt = `You are a professional localization expert. Your task is to translate UI keys for a Windows Optimization application.
Translate the following JSON object's values into ${targetLangName} (${targetLang}).
Return ONLY a valid JSON object with the exact same keys but translated values. Keep formatting tokens like {prefix} untouched. Do not add markdown blocks like \`\`\`json.`;

        // We only send the keys that need translation along with their reference (e.g. English/Turkish) values.
        const inputObject: Record<string, string> = {};
        for (const key of keysToTranslate) {
            if (referenceTranslations[key]) {
                inputObject[key] = referenceTranslations[key];
            }
        }

        if (Object.keys(inputObject).length === 0) {
            return NextResponse.json({ translations: {} });
        }

        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                contents: [
                    { role: "user", parts: [{ text: systemPrompt + "\n\n" + JSON.stringify(inputObject, null, 2) }] }
                ],
                generationConfig: {
                    responseMimeType: "application/json",
                    temperature: 0.1
                }
            })
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Gemini API Error: ${err}`);
        }

        const data = await response.json();
        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
        
        if (!generatedText) {
            throw new Error("No text generated by AI");
        }

        const parsedTranslations = JSON.parse(generatedText);
        
        // Ensure we only return the requested keys to prevent malicious injections
        const cleanedTranslations: Record<string, string> = {};
        for (const key of keysToTranslate) {
            if (parsedTranslations[key]) {
                cleanedTranslations[key] = parsedTranslations[key];
            }
        }

        return NextResponse.json({ translations: cleanedTranslations });
    } catch (error) {
        console.error("[AI Auto-Translate ERROR]", error);
        return NextResponse.json({ error: "Failed to translate via AI", details: (error as Error).message }, { status: 500 });
    }
}
