"use client";

import { useOptWinStore } from "@/store/useOptWinStore";
import { useTranslation } from "@/i18n/useTranslation";
import Link from "next/link";
import { ArrowLeftIcon, BookOpenIcon } from "@/components/shared/Icons";

const content: Record<string, { disclaimer?: string; lastUpdated: string; sections: { title: string; content: string[] }[] }> = {
    en: {
        lastUpdated: "March 2026",
        sections: [
            { title: "1. Acceptance of Terms", content: ["By accessing and using OptWin (\"Service\"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use this Service."] },
            {
                title: "2. Description of Service", content: [
                    "OptWin is a free, open-source Windows optimization tool that generates PowerShell scripts based on user-selected features. The scripts are designed to optimize Windows system settings for better performance.",
                ]
            },
            {
                title: "3. Usage License", content: [
                    "Permission is granted to use OptWin for personal and commercial purposes. Under this license, you may:",
                    "Generate and download optimization scripts for your own systems.",
                    "Share the generated scripts with others.",
                    "Inspect and contribute to the source code on GitHub.",
                    "You may not reverse-engineer, decompile, or attempt to extract the source code of the web application beyond what is publicly available.",
                ]
            },
            {
                title: "4. Disclaimer of Warranties", content: [
                    "OptWin is provided 'as is' without warranty of any kind, express or implied. We make no guarantees regarding:",
                    "The accuracy, reliability, or completeness of the generated scripts.",
                    "The suitability of the scripts for any particular purpose.",
                    "That the Service will be uninterrupted, error-free, or secure.",
                    "That the scripts will not cause any adverse effects on your system.",
                ]
            },
            {
                title: "5. Limitation of Liability", content: [
                    "In no event shall OptWin, its developers, or contributors be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:",
                    "Your use or inability to use the Service.",
                    "Any system damage caused by running the generated scripts.",
                    "Loss of data, profits, or business interruption.",
                    "Any unauthorized access to your system.",
                    "Always create a System Restore Point before running any optimization script. This is your responsibility.",
                ]
            },
            {
                title: "6. User Responsibilities", content: [
                    "You agree to:",
                    "Use the Service in compliance with all applicable laws and regulations.",
                    "Create a system restore point before running any generated script.",
                    "Review the contents of scripts before execution.",
                    "Not use the Service for any malicious, harmful, or illegal purposes.",
                    "Not attempt to disrupt or interfere with the Service or its infrastructure.",
                ]
            },
            {
                title: "7. Generated Scripts", content: [
                    "Scripts generated by OptWin modify Windows system settings. By generating and executing a script, you acknowledge that:",
                    "You understand the changes the script will make.",
                    "You accept full responsibility for any consequences.",
                    "You have the authority to make changes on the target system.",
                    "The scripts should be run on personal systems only, not on shared or enterprise systems without proper authorization.",
                ]
            },
            {
                title: "8. Intellectual Property", content: [
                    "OptWin's source code is publicly available on GitHub under an open-source license. The OptWin name, logo, and branding are the property of the developer.",
                ]
            },
            {
                title: "9. Third-Party Links", content: [
                    "Our Service may contain links to third-party websites. We are not responsible for the content, privacy policies, or practices of any third-party sites. We encourage you to review their policies before providing any personal information.",
                ]
            },
            {
                title: "10. Modifications to Terms", content: [
                    "We reserve the right to modify these Terms of Service at any time. Changes will become effective immediately upon posting on the website. Your continued use of the Service after the revised Terms are posted constitutes your acceptance of the changes.",
                ]
            },
            {
                title: "11. Termination", content: [
                    "We reserve the right to terminate or restrict access to the Service at any time, without prior notice, for any reason including but not limited to violation of these Terms.",
                ]
            },
            {
                title: "12. Severability", content: [
                    "If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.",
                ]
            },
            {
                title: "13. Governing Law", content: [
                    "These Terms of Service shall be governed by and construed in accordance with the laws of the Republic of Turkey. You irrevocably submit to the exclusive jurisdiction of the courts of Istanbul for any dispute arising from these Terms.",
                ]
            },
            {
                title: "14. Contact", content: [
                    "If you have questions about these Terms of Service, please contact us via the Contact page on our website.",
                ]
            },
        ],
    },
    tr: {
        disclaimer: "Bu bir çeviridir. Uyuşmazlık durumunda İngilizce sürüm geçerlidir.",
        lastUpdated: "Mart 2026",
        sections: [
            { title: "1. Şartların Kabulü", content: ["OptWin'e (\"Hizmet\") erişerek ve kullanarak, bu Kullanım Şartlarının hükümlerine bağlı kalmayı kabul edersiniz. Bu şartları kabul etmiyorsanız, lütfen bu Hizmeti kullanmayın."] },
            {
                title: "2. Hizmet Açıklaması", content: [
                    "OptWin, kullanıcının seçtiği özelliklere göre PowerShell scriptleri oluşturan ücretsiz, açık kaynaklı bir Windows optimizasyon aracıdır. Scriptler, daha iyi performans için Windows sistem ayarlarını optimize etmek üzere tasarlanmıştır.",
                ]
            },
            {
                title: "3. Kullanım Lisansı", content: [
                    "OptWin'i kişisel ve ticari amaçlarla kullanma izni verilir. Bu lisans kapsamında:",
                    "Kendi sistemleriniz için optimizasyon scriptleri oluşturabilir ve indirebilirsiniz.",
                    "Oluşturulan scriptleri başkalarıyla paylaşabilirsiniz.",
                    "GitHub'da kaynak kodu inceleyebilir ve katkıda bulunabilirsiniz.",
                    "Kamuya açık olanın ötesinde web uygulamasının kaynak kodunu tersine mühendislik yapamaz veya çıkartamazsınız.",
                ]
            },
            {
                title: "4. Garanti Reddi", content: [
                    "OptWin, açık veya zımni hiçbir garanti olmaksızın \"olduğu gibi\" sağlanmaktadır. Şunları garanti etmiyoruz:",
                    "Oluşturulan scriptlerin doğruluğu, güvenilirliği veya eksiksizliği.",
                    "Scriptlerin herhangi bir amaca uygunluğu.",
                    "Hizmetin kesintisiz, hatasız veya güvenli olacağı.",
                    "Scriptlerin sisteminizde olumsuz etkilere neden olmayacağı.",
                ]
            },
            {
                title: "5. Sorumluluk Sınırlaması", content: [
                    "Hiçbir durumda OptWin, geliştiricileri veya katkıda bulunanlar şunlardan kaynaklanan herhangi bir doğrudan, dolaylı, arızi, özel, sonuçsal veya cezai hasardan sorumlu tutulamaz:",
                    "Hizmeti kullanımınız veya kullanamamanız.",
                    "Oluşturulan scriptlerin çalıştırılmasından kaynaklanan herhangi bir sistem hasarı.",
                    "Veri, kar kaybı veya iş kesintisi.",
                    "Sisteminize herhangi bir yetkisiz erişim.",
                    "Herhangi bir optimizasyon scripti çalıştırmadan önce mutlaka bir Sistem Geri Yükleme Noktası oluşturun. Bu sizin sorumluluğunuzdur.",
                ]
            },
            {
                title: "6. Kullanıcı Sorumlulukları", content: [
                    "Şunları kabul edersiniz:",
                    "Hizmeti tüm geçerli yasa ve düzenlemelere uygun olarak kullanmak.",
                    "Oluşturulan herhangi bir scripti çalıştırmadan önce sistem geri yükleme noktası oluşturmak.",
                    "Çalıştırmadan önce scriptlerin içeriğini incelemek.",
                    "Hizmeti kötü niyetli, zararlı veya yasadışı amaçlarla kullanmamak.",
                    "Hizmeti veya altyapısını bozmaya veya engellemeye çalışmamak.",
                ]
            },
            {
                title: "7. Oluşturulan Scriptler", content: [
                    "OptWin tarafından oluşturulan scriptler Windows sistem ayarlarını değiştirir. Bir script oluşturarak ve çalıştırarak şunları kabul edersiniz:",
                    "Scriptin yapacağı değişiklikleri anladığınızı.",
                    "Herhangi bir sonuç için tam sorumluluğu kabul ettiğinizi.",
                    "Hedef sistemde değişiklik yapma yetkiniz olduğunu.",
                    "Scriptlerin uygun yetkilendirme olmadan paylaşılan veya kurumsal sistemlerde değil, yalnızca kişisel sistemlerde çalıştırılması gerektiğini.",
                ]
            },
            {
                title: "8. Fikri Mülkiyet", content: [
                    "OptWin'in kaynak kodu GitHub'da açık kaynak lisansı altında kamuya açıktır. OptWin adı, logosu ve markası geliştiricinin mülkiyetindedir.",
                ]
            },
            {
                title: "9. Üçüncü Taraf Bağlantıları", content: [
                    "Hizmetimiz üçüncü taraf web sitelerine bağlantılar içerebilir. Üçüncü taraf sitelerinin içeriğinden, gizlilik politikalarından veya uygulamalarından sorumlu değiliz.",
                ]
            },
            {
                title: "10. Şartlarda Değişiklikler", content: [
                    "Bu Kullanım Şartlarını herhangi bir zamanda değiştirme hakkını saklı tutarız. Değişiklikler web sitesinde yayınlandıktan hemen sonra yürürlüğe girecektir. Revize edilmiş Şartların yayınlanmasının ardından Hizmeti kullanmaya devam etmeniz, değişiklikleri kabul ettiğiniz anlamına gelir.",
                ]
            },
            {
                title: "11. Fesih", content: [
                    "Bu Şartların ihlali dahil ancak bununla sınırlı olmamak üzere herhangi bir nedenle, önceden bildirim vermeksizin Hizmete erişimi sonlandırma veya kısıtlama hakkını saklı tutarız.",
                ]
            },
            {
                title: "12. Bölünebilirlik", content: [
                    "Bu Şartların herhangi bir hükmü geçersiz veya uygulanamaz bulunursa, kalan hükümler tam olarak yürürlükte kalacaktır.",
                ]
            },
            {
                title: "13. Geçerli Hukuk", content: [
                    "Bu Kullanım Şartları Türkiye Cumhuriyeti yasalarına tabidir. Bu Şartlardan kaynaklanan herhangi bir anlaşmazlık için İstanbul Mahkemelerinin münhasır yargı yetkisini kabul edersiniz.",
                ]
            },
            {
                title: "14. İletişim", content: [
                    "Bu Kullanım Şartları hakkında sorularınız varsa, lütfen web sitemizdeki İletişim sayfası aracılığıyla bizimle iletişime geçin.",
                ]
            },
        ],
    },
    de: {
        disclaimer: "Dies ist eine Übersetzung. Im Falle von Unstimmigkeiten gilt die englische Version.",
        lastUpdated: "März 2026",
        sections: [
            { title: "1. Annahme der Bedingungen", content: ["Durch den Zugriff auf OptWin stimmen Sie diesen Nutzungsbedingungen zu."] },
            { title: "2. Beschreibung des Dienstes", content: ["OptWin ist ein kostenloses Open-Source Windows-Optimierungstool, das PowerShell-Skripte generiert."] },
            { title: "3. Nutzungslizenz", content: ["OptWin darf für persönliche und kommerzielle Zwecke verwendet werden. Skripte dürfen geteilt werden. Quellcode ist auf GitHub verfügbar."] },
            { title: "4. Haftungsausschluss", content: ["OptWin wird ohne jegliche Garantie bereitgestellt. Wir garantieren keine Genauigkeit, Zuverlässigkeit oder Fehlerfreiheit."] },
            { title: "5. Haftungsbeschränkung", content: ["Wir haften nicht für Schäden durch die Nutzung des Dienstes oder generierter Skripte. Erstellen Sie immer einen Systemwiederherstellungspunkt."] },
            { title: "6. Nutzerpflichten", content: ["Nutzen Sie den Dienst gesetzeskonform, erstellen Sie Wiederherstellungspunkte und prüfen Sie Skripte vor der Ausführung."] },
            { title: "7. Generierte Skripte", content: ["Skripte ändern Windows-Einstellungen. Sie übernehmen die volle Verantwortung für alle Konsequenzen."] },
            { title: "8. Geistiges Eigentum", content: ["Der Quellcode ist auf GitHub öffentlich verfügbar. Name und Logo sind Eigentum des Entwicklers."] },
            { title: "9. Änderungen", content: ["Wir behalten uns das Recht vor, diese Bedingungen jederzeit zu ändern."] },
            { title: "10. Geltendes Recht", content: ["Es gilt das Recht der Republik Türkei. Gerichtsstand ist Istanbul."] },
            { title: "11. Kontakt", content: ["Bei Fragen nutzen Sie bitte unsere Kontaktseite."] },
        ],
    },
    fr: {
        disclaimer: "Ceci est une traduction. En cas de divergence, la version anglaise prévaut.",
        lastUpdated: "Mars 2026",
        sections: [
            { title: "1. Acceptation des Conditions", content: ["En accédant à OptWin, vous acceptez ces Conditions d'Utilisation."] },
            { title: "2. Description du Service", content: ["OptWin est un outil gratuit et open source d'optimisation Windows qui génère des scripts PowerShell."] },
            { title: "3. Licence d'Utilisation", content: ["Vous pouvez utiliser OptWin à des fins personnelles et commerciales. Les scripts peuvent être partagés. Le code source est disponible sur GitHub."] },
            { title: "4. Avertissement", content: ["OptWin est fourni 'tel quel' sans aucune garantie. Nous ne garantissons pas l'exactitude ou la fiabilité."] },
            { title: "5. Limitation de Responsabilité", content: ["Nous ne sommes pas responsables des dommages causés par l'utilisation du Service ou des scripts. Créez toujours un point de restauration."] },
            { title: "6. Responsabilités de l'Utilisateur", content: ["Utilisez le Service conformément à la loi, créez des points de restauration et vérifiez les scripts avant exécution."] },
            { title: "7. Scripts Générés", content: ["Les scripts modifient les paramètres Windows. Vous assumez l'entière responsabilité des conséquences."] },
            { title: "8. Propriété Intellectuelle", content: ["Le code source est publiquement disponible sur GitHub. Le nom et logo sont la propriété du développeur."] },
            { title: "9. Modifications", content: ["Nous nous réservons le droit de modifier ces conditions à tout moment."] },
            { title: "10. Droit Applicable", content: ["Ces conditions sont régies par les lois de la République de Turquie. Juridiction exclusive: Istanbul."] },
            { title: "11. Contact", content: ["Pour toute question, utilisez notre page de contact."] },
        ],
    },
    zh: {
        disclaimer: "这是翻译版本。如有歧义，以英文版本为准。",
        lastUpdated: "2026年3月",
        sections: [
            { title: "1. 条款接受", content: ["使用OptWin即表示您同意这些服务条款。"] },
            { title: "2. 服务说明", content: ["OptWin是一个免费开源的Windows优化工具，生成PowerShell脚本。"] },
            { title: "3. 免责声明", content: ["OptWin按「原样」提供，不提供任何保证。运行脚本前务必创建系统还原点。"] },
            { title: "4. 责任限制", content: ["我们不对使用服务或脚本造成的损害负责。"] },
            { title: "5. 用户责任", content: ["合法使用服务，创建还原点，执行前检查脚本。"] },
            { title: "6. 适用法律", content: ["受土耳其共和国法律管辖。管辖法院：伊斯坦布尔。"] },
            { title: "7. 联系方式", content: ["如有问题，请通过联系页面与我们联系。"] },
        ],
    },
    es: {
        disclaimer: "Esta es una traducción. En caso de discrepancia, prevalece la versión en inglés.",
        lastUpdated: "Marzo 2026",
        sections: [
            { title: "1. Aceptación", content: ["Al usar OptWin, acepta estos Términos de Servicio."] },
            { title: "2. Descripción del Servicio", content: ["OptWin es una herramienta gratuita de código abierto para optimización de Windows que genera scripts PowerShell."] },
            { title: "3. Exención de Responsabilidad", content: ["OptWin se proporciona 'tal cual' sin garantía. Cree siempre un punto de restauración antes de ejecutar scripts."] },
            { title: "4. Limitación de Responsabilidad", content: ["No somos responsables de daños causados por el uso del Servicio o scripts."] },
            { title: "5. Responsabilidades del Usuario", content: ["Use el Servicio legalmente, cree puntos de restauración y revise los scripts antes de ejecutarlos."] },
            { title: "6. Ley Aplicable", content: ["Regido por las leyes de la República de Turquía. Jurisdicción: Estambul."] },
            { title: "7. Contacto", content: ["Para preguntas, use nuestra página de contacto."] },
        ],
    },
    hi: {
        disclaimer: "यह एक अनुवाद है। विसंगति की स्थिति में अंग्रेजी संस्करण मान्य होगा।",
        lastUpdated: "मार्च 2026",
        sections: [
            { title: "1. शर्तों की स्वीकृति", content: ["OptWin का उपयोग करके, आप इन सेवा शर्तों से सहमत होते हैं।"] },
            { title: "2. सेवा विवरण", content: ["OptWin एक मुफ्त, ओपन-सोर्स Windows अनुकूलन उपकरण है जो PowerShell स्क्रिप्ट जनरेट करता है।"] },
            { title: "3. अस्वीकरण", content: ["OptWin बिना किसी गारंटी के प्रदान किया जाता है। स्क्रिप्ट चलाने से पहले हमेशा सिस्टम रिस्टोर पॉइंट बनाएं।"] },
            { title: "4. दायित्व सीमा", content: ["सेवा या स्क्रिप्ट के उपयोग से होने वाले नुकसान के लिए हम जिम्मेदार नहीं हैं।"] },
            { title: "5. उपयोगकर्ता जिम्मेदारियां", content: ["कानूनी रूप से सेवा का उपयोग करें, रिस्टोर पॉइंट बनाएं और निष्पादन से पहले स्क्रिप्ट की समीक्षा करें।"] },
            { title: "6. लागू कानून", content: ["तुर्की गणराज्य के कानूनों द्वारा शासित। न्यायालय: इस्तांबुल।"] },
            { title: "7. संपर्क", content: ["प्रश्नों के लिए, हमारे संपर्क पृष्ठ का उपयोग करें।"] },
        ],
    },
};

export default function Terms() {
    const lang = useOptWinStore((s) => s.lang);
    const { t } = useTranslation();
    const data = content[lang] || content.en;

    return (
        <div className="flex flex-col items-center w-full animate-fade-in-up mt-8 mb-16">
            <div className="w-full max-w-3xl px-4">
                {/* Header */}
                <div className="text-center mb-10">
                    <div className="size-16 rounded-2xl bg-[var(--accent-color)]/10 text-[var(--accent-color)] flex items-center justify-center mx-auto mb-4">
                        <BookOpenIcon size={28} />
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold mb-4 text-[var(--text-primary)]">
                        {t["terms.title"]}
                    </h1>
                    {data.disclaimer && (
                        <p className="text-sm text-amber-500/80 bg-amber-500/10 border border-amber-500/20 rounded-xl px-4 py-2 inline-block mb-4">
                            {data.disclaimer}
                        </p>
                    )}
                </div>

                {/* Sections */}
                <div className="space-y-6">
                    {data.sections.map((section, i) => (
                        <div key={i} className="bg-[var(--card-bg)] border border-[var(--border-color)] p-6 rounded-2xl">
                            <h2 className="text-lg font-bold text-[var(--text-primary)] mb-3">
                                {section.title}
                            </h2>
                            <div className="space-y-2">
                                {section.content.map((line, j) => (
                                    <p key={j} className="text-sm text-[var(--text-secondary)] leading-relaxed">
                                        {line}
                                    </p>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>

                {/* Last updated */}
                <p className="text-center text-xs text-[var(--text-secondary)] mt-6">
                    {lang === "tr" ? "Son Güncelleme" : lang === "de" ? "Letzte Aktualisierung" : lang === "fr" ? "Dernière mise à jour" : "Last Updated"}: {data.lastUpdated}
                </p>

                {/* Back link */}
                <div className="mt-6 text-center">
                    <Link
                        href="/"
                        className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[var(--border-color)]/50 text-[var(--text-primary)] font-semibold hover:bg-[var(--border-color)] transition-all"
                    >
                        <ArrowLeftIcon size={16} />
                        {t["contact.backHome"]}
                    </Link>
                </div>
            </div>
        </div>
    );
}
