/**
 * Default language data for seeding the Language model.
 * This replaces all hardcoded LANGS, FLAG_SVG, and UTC_OFFSET constants.
 */
export const defaultLanguages = [
    {
        code: "tr",
        name: "Turkish",
        nativeName: "Türkçe",
        utcOffset: 3,
        isDefault: true,
        isActive: true,
        sortOrder: 0,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#E30A17" width="30" height="20"/><circle cx="11" cy="10" r="6" fill="white"/><circle cx="13" cy="10" r="5" fill="#E30A17"/><polygon fill="white" points="17,10 14.09,8.09 15.18,11.45 13.09,9.54 16.45,10.73"/></svg>`,
        seoMetadata: { title: "OptWin - Windows Optimizasyon Aracı", description: "Windows bilgisayarınızı optimize edin", keywords: "windows, optimizasyon, hız" },
    },
    {
        code: "en",
        name: "English",
        nativeName: "English",
        utcOffset: 0,
        isDefault: false,
        isActive: true,
        sortOrder: 1,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#012169" width="30" height="20"/><path d="M0,0 L30,20 M30,0 L0,20" stroke="white" stroke-width="4"/><path d="M0,0 L30,20 M30,0 L0,20" stroke="#C8102E" stroke-width="2"/><path d="M15,0 V20 M0,10 H30" stroke="white" stroke-width="6"/><path d="M15,0 V20 M0,10 H30" stroke="#C8102E" stroke-width="3"/></svg>`,
        seoMetadata: { title: "OptWin - Windows Optimization Tool", description: "Optimize your Windows PC with one click", keywords: "windows, optimization, performance" },
    },
    {
        code: "de",
        name: "German",
        nativeName: "Deutsch",
        utcOffset: 1,
        isDefault: false,
        isActive: true,
        sortOrder: 2,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#000" width="30" height="6.67"/><rect fill="#DD0000" y="6.67" width="30" height="6.67"/><rect fill="#FFCC00" y="13.33" width="30" height="6.67"/></svg>`,
        seoMetadata: { title: "OptWin - Windows-Optimierungstool", description: "Optimieren Sie Ihren Windows-PC", keywords: "windows, optimierung, leistung" },
    },
    {
        code: "fr",
        name: "French",
        nativeName: "Français",
        utcOffset: 1,
        isDefault: false,
        isActive: true,
        sortOrder: 3,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#002395" width="10" height="20"/><rect fill="white" x="10" width="10" height="20"/><rect fill="#ED2939" x="20" width="10" height="20"/></svg>`,
        seoMetadata: { title: "OptWin - Outil d'optimisation Windows", description: "Optimisez votre PC Windows", keywords: "windows, optimisation, performance" },
    },
    {
        code: "es",
        name: "Spanish",
        nativeName: "Español",
        utcOffset: 1,
        isDefault: false,
        isActive: true,
        sortOrder: 4,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#AA151B" width="30" height="5"/><rect fill="#F1BF00" y="5" width="30" height="10"/><rect fill="#AA151B" y="15" width="30" height="5"/></svg>`,
        seoMetadata: { title: "OptWin - Herramienta de optimización de Windows", description: "Optimice su PC con Windows", keywords: "windows, optimización, rendimiento" },
    },
    {
        code: "zh",
        name: "Chinese",
        nativeName: "中文",
        utcOffset: 8,
        isDefault: false,
        isActive: true,
        sortOrder: 5,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#DE2910" width="30" height="20"/><polygon fill="#FFDE00" points="5,2.5 6.1,5.9 3.1,3.9 6.9,3.9 3.9,5.9"/><polygon fill="#FFDE00" points="10,1 10.5,2.3 9.2,1.5 10.8,1.5 9.5,2.3" transform="scale(0.6) translate(10,0)"/><polygon fill="#FFDE00" points="12,3 12.5,4.3 11.2,3.5 12.8,3.5 11.5,4.3" transform="scale(0.6) translate(10,0)"/></svg>`,
        seoMetadata: { title: "OptWin - Windows 优化工具", description: "一键优化您的 Windows 电脑", keywords: "windows, 优化, 性能" },
    },
    {
        code: "hi",
        name: "Hindi",
        nativeName: "हिन्दी",
        utcOffset: 5.5,
        isDefault: false,
        isActive: true,
        sortOrder: 6,
        flagSvg: `<svg viewBox="0 0 30 20" width="16" height="11"><rect fill="#FF9933" width="30" height="6.67"/><rect fill="white" y="6.67" width="30" height="6.67"/><rect fill="#138808" y="13.33" width="30" height="6.67"/><circle cx="15" cy="10" r="2" fill="none" stroke="#000080" stroke-width="0.5"/></svg>`,
        seoMetadata: { title: "OptWin - विंडोज़ ऑप्टिमाइज़ेशन टूल", description: "एक क्लिक में अपने विंडोज़ पीसी को ऑप्टिमाइज़ करें", keywords: "windows, ऑप्टिमाइज़ेशन, प्रदर्शन" },
    },
];
