export const scriptLabels: { lang: string; key: string; value: string }[] = [
    // ── English ──
    { lang: "en", key: "scriptTitle", value: "OptWin - Windows Optimization Script" },
    { lang: "en", key: "version", value: "Version" },
    { lang: "en", key: "date", value: "Date" },
    { lang: "en", key: "developer", value: "Developer" },
    { lang: "en", key: "website", value: "Website" },
    { lang: "en", key: "openSource", value: "This script is open source and free to use." },
    { lang: "en", key: "bannerTitle", value: "Windows Optimization Script" },
    { lang: "en", key: "openSourceShort", value: "Open Source | Free to Use" },
    { lang: "en", key: "adminRequest", value: "[INFO] Requesting Administrator privileges..." },
    { lang: "en", key: "adminPrompt", value: "Please click Yes on the UAC prompt." },
    { lang: "en", key: "adminError", value: "[ERROR] Could not elevate to Administrator." },
    { lang: "en", key: "adminHint", value: "Please right-click the script and select Run with PowerShell" },
    { lang: "en", key: "pressAnyKey", value: "Press any key to exit..." },
    { lang: "en", key: "restorePoint", value: "Creating System Restore Point..." },
    { lang: "en", key: "restoreSuccess", value: "Restore point created successfully." },
    { lang: "en", key: "restoreFail", value: "Failed to create restore point. Check system settings." },
    { lang: "en", key: "complete", value: "OPTIMIZATION COMPLETE" },
    { lang: "en", key: "success", value: "System reboot is recommended to apply all changes." },
    { lang: "en", key: "thankYou", value: "Thank you for using OptWin!" },
    { lang: "en", key: "author", value: "Developed by ahmetly_" },
    { lang: "en", key: "done", value: "Done" },
    { lang: "en", key: "developerName", value: "ahmetly" },
    { lang: "en", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "en", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },

    // ── Turkish ──
    { lang: "tr", key: "scriptTitle", value: "OptWin - Windows Optimizasyon Scripti" },
    { lang: "tr", key: "version", value: "Versiyon" },
    { lang: "tr", key: "date", value: "Tarih" },
    { lang: "tr", key: "developer", value: "Gelistirici" },
    { lang: "tr", key: "website", value: "Website" },
    { lang: "tr", key: "openSource", value: "Bu script acik kaynaklidir ve ucretsiz kullanilabilir." },
    { lang: "tr", key: "bannerTitle", value: "Windows Optimizasyon Scripti" },
    { lang: "tr", key: "openSourceShort", value: "Acik Kaynak | Ucretsiz" },
    { lang: "tr", key: "adminRequest", value: "[BILGI] Yonetici izni isteniyor..." },
    { lang: "tr", key: "adminPrompt", value: "Lutfen UAC penceresinde Evet i tiklayin." },
    { lang: "tr", key: "adminError", value: "[HATA] Yonetici olarak calistirilamadi." },
    { lang: "tr", key: "adminHint", value: "Lutfen scripte sag tiklayin ve PowerShell ile Calistir secin" },
    { lang: "tr", key: "pressAnyKey", value: "Cikmak icin herhangi bir tusa basin..." },
    { lang: "tr", key: "restorePoint", value: "Sistem Geri Yukleme Noktasi olusturuluyor..." },
    { lang: "tr", key: "restoreSuccess", value: "Geri yukleme noktasi basariyla olusturuldu." },
    { lang: "tr", key: "restoreFail", value: "Geri yukleme noktasi olusturulamadi. Sistem ayarlarini kontrol edin." },
    { lang: "tr", key: "complete", value: "OPTIMIZASYON TAMAMLANDI" },
    { lang: "tr", key: "success", value: "Tum degisikliklerin uygulanmasi icin sistemi yeniden baslatmaniz onerilir." },
    { lang: "tr", key: "thankYou", value: "OptWin i kullandiginiz icin tesekkurler!" },
    { lang: "tr", key: "author", value: "ahmetly_ tarafindan gelistirildi" },
    { lang: "tr", key: "done", value: "Tamamlandi" },
    { lang: "tr", key: "developerName", value: "ahmetly" },
    { lang: "tr", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "tr", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },

    // ── Chinese ──
    { lang: "zh", key: "scriptTitle", value: "OptWin - Windows 优化脚本" },
    { lang: "zh", key: "version", value: "版本" },
    { lang: "zh", key: "date", value: "日期" },
    { lang: "zh", key: "developer", value: "开发者" },
    { lang: "zh", key: "website", value: "网站" },
    { lang: "zh", key: "openSource", value: "此脚本是开源的，可免费使用。" },
    { lang: "zh", key: "bannerTitle", value: "Windows 优化脚本" },
    { lang: "zh", key: "openSourceShort", value: "开源 | 免费使用" },
    { lang: "zh", key: "adminRequest", value: "[信息] 正在请求管理员权限..." },
    { lang: "zh", key: "adminPrompt", value: "请在 UAC 提示中点击\"是\"。" },
    { lang: "zh", key: "adminError", value: "[错误] 无法提升为管理员。" },
    { lang: "zh", key: "adminHint", value: "请右键点击脚本并选择\"使用 PowerShell 运行\"" },
    { lang: "zh", key: "pressAnyKey", value: "按任意键退出..." },
    { lang: "zh", key: "restorePoint", value: "正在创建系统还原点..." },
    { lang: "zh", key: "restoreSuccess", value: "还原点创建成功。" },
    { lang: "zh", key: "restoreFail", value: "创建还原点失败。请检查系统设置。" },
    { lang: "zh", key: "complete", value: "优化完成" },
    { lang: "zh", key: "success", value: "建议重启系统以应用所有更改。" },
    { lang: "zh", key: "thankYou", value: "感谢您使用 OptWin！" },
    { lang: "zh", key: "author", value: "由 ahmetly_ 开发" },
    { lang: "zh", key: "done", value: "完成" },
    { lang: "zh", key: "developerName", value: "ahmetly" },
    { lang: "zh", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "zh", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },

    // ── Spanish ──
    { lang: "es", key: "scriptTitle", value: "OptWin - Script de Optimización de Windows" },
    { lang: "es", key: "version", value: "Versión" },
    { lang: "es", key: "date", value: "Fecha" },
    { lang: "es", key: "developer", value: "Desarrollador" },
    { lang: "es", key: "website", value: "Sitio Web" },
    { lang: "es", key: "openSource", value: "Este script es de código abierto y de uso gratuito." },
    { lang: "es", key: "bannerTitle", value: "Script de Optimización de Windows" },
    { lang: "es", key: "openSourceShort", value: "Código Abierto | Uso Gratuito" },
    { lang: "es", key: "adminRequest", value: "[INFO] Solicitando privilegios de Administrador..." },
    { lang: "es", key: "adminPrompt", value: "Por favor, haga clic en Sí en el aviso UAC." },
    { lang: "es", key: "adminError", value: "[ERROR] No se pudo elevar a Administrador." },
    { lang: "es", key: "adminHint", value: "Haga clic derecho en el script y seleccione Ejecutar con PowerShell" },
    { lang: "es", key: "pressAnyKey", value: "Presione cualquier tecla para salir..." },
    { lang: "es", key: "restorePoint", value: "Creando Punto de Restauración del Sistema..." },
    { lang: "es", key: "restoreSuccess", value: "Punto de restauración creado exitosamente." },
    { lang: "es", key: "restoreFail", value: "Error al crear punto de restauración. Verifique la configuración del sistema." },
    { lang: "es", key: "complete", value: "OPTIMIZACIÓN COMPLETA" },
    { lang: "es", key: "success", value: "Se recomienda reiniciar el sistema para aplicar todos los cambios." },
    { lang: "es", key: "thankYou", value: "¡Gracias por usar OptWin!" },
    { lang: "es", key: "author", value: "Desarrollado por ahmetly_" },
    { lang: "es", key: "done", value: "Hecho" },
    { lang: "es", key: "developerName", value: "ahmetly" },
    { lang: "es", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "es", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },

    // ── Hindi ──
    { lang: "hi", key: "scriptTitle", value: "OptWin - Windows ऑप्टिमाइज़ेशन स्क्रिप्ट" },
    { lang: "hi", key: "version", value: "संस्करण" },
    { lang: "hi", key: "date", value: "तिथि" },
    { lang: "hi", key: "developer", value: "डेवलपर" },
    { lang: "hi", key: "website", value: "वेबसाइट" },
    { lang: "hi", key: "openSource", value: "यह स्क्रिप्ट ओपन सोर्स है और मुफ्त में उपलब्ध है।" },
    { lang: "hi", key: "bannerTitle", value: "Windows ऑप्टिमाइज़ेशन स्क्रिप्ट" },
    { lang: "hi", key: "openSourceShort", value: "ओपन सोर्स | मुफ्त" },
    { lang: "hi", key: "adminRequest", value: "[जानकारी] एडमिनिस्ट्रेटर अनुमति का अनुरोध किया जा रहा है..." },
    { lang: "hi", key: "adminPrompt", value: "कृपया UAC प्रॉम्प्ट पर हाँ क्लिक करें।" },
    { lang: "hi", key: "adminError", value: "[त्रुटि] एडमिनिस्ट्रेटर नहीं बन सके।" },
    { lang: "hi", key: "adminHint", value: "कृपया स्क्रिप्ट पर राइट-क्लिक करें और PowerShell से चलाएं चुनें" },
    { lang: "hi", key: "pressAnyKey", value: "बाहर निकलने के लिए कोई भी कुंजी दबाएं..." },
    { lang: "hi", key: "restorePoint", value: "सिस्टम रिस्टोर पॉइंट बनाया जा रहा है..." },
    { lang: "hi", key: "restoreSuccess", value: "रिस्टोर पॉइंट सफलतापूर्वक बनाया गया।" },
    { lang: "hi", key: "restoreFail", value: "रिस्टोर पॉइंट बनाने में विफल। सिस्टम सेटिंग्स जांचें।" },
    { lang: "hi", key: "complete", value: "ऑप्टिमाइज़ेशन पूर्ण" },
    { lang: "hi", key: "success", value: "सभी परिवर्तन लागू करने के लिए सिस्टम रीबूट की सिफारिश की जाती है।" },
    { lang: "hi", key: "thankYou", value: "OptWin का उपयोग करने के लिए धन्यवाद!" },
    { lang: "hi", key: "author", value: "ahmetly_ द्वारा विकसित" },
    { lang: "hi", key: "done", value: "पूर्ण" },
    { lang: "hi", key: "developerName", value: "ahmetly" },
    { lang: "hi", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "hi", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },

    // ── German ──
    { lang: "de", key: "scriptTitle", value: "OptWin - Windows-Optimierungsskript" },
    { lang: "de", key: "version", value: "Version" },
    { lang: "de", key: "date", value: "Datum" },
    { lang: "de", key: "developer", value: "Entwickler" },
    { lang: "de", key: "website", value: "Webseite" },
    { lang: "de", key: "openSource", value: "Dieses Skript ist Open Source und kostenlos nutzbar." },
    { lang: "de", key: "bannerTitle", value: "Windows-Optimierungsskript" },
    { lang: "de", key: "openSourceShort", value: "Open Source | Kostenlos" },
    { lang: "de", key: "adminRequest", value: "[INFO] Administratorrechte werden angefordert..." },
    { lang: "de", key: "adminPrompt", value: "Bitte klicken Sie im UAC-Dialog auf Ja." },
    { lang: "de", key: "adminError", value: "[FEHLER] Konnte nicht als Administrator starten." },
    { lang: "de", key: "adminHint", value: "Bitte klicken Sie mit der rechten Maustaste auf das Skript und waehlen Sie Mit PowerShell ausfuehren" },
    { lang: "de", key: "pressAnyKey", value: "Druecken Sie eine beliebige Taste zum Beenden..." },
    { lang: "de", key: "restorePoint", value: "Systemwiederherstellungspunkt wird erstellt..." },
    { lang: "de", key: "restoreSuccess", value: "Wiederherstellungspunkt erfolgreich erstellt." },
    { lang: "de", key: "restoreFail", value: "Wiederherstellungspunkt konnte nicht erstellt werden." },
    { lang: "de", key: "complete", value: "OPTIMIERUNG ABGESCHLOSSEN" },
    { lang: "de", key: "success", value: "Ein Systemneustart wird empfohlen, um alle Aenderungen anzuwenden." },
    { lang: "de", key: "thankYou", value: "Vielen Dank fuer die Nutzung von OptWin!" },
    { lang: "de", key: "author", value: "Entwickelt von ahmetly_" },
    { lang: "de", key: "done", value: "Erledigt" },
    { lang: "de", key: "developerName", value: "ahmetly" },
    { lang: "de", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "de", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },

    // ── French ──
    { lang: "fr", key: "scriptTitle", value: "OptWin - Script d'Optimisation Windows" },
    { lang: "fr", key: "version", value: "Version" },
    { lang: "fr", key: "date", value: "Date" },
    { lang: "fr", key: "developer", value: "Developpeur" },
    { lang: "fr", key: "website", value: "Site Web" },
    { lang: "fr", key: "openSource", value: "Ce script est open source et gratuit." },
    { lang: "fr", key: "bannerTitle", value: "Script d'Optimisation Windows" },
    { lang: "fr", key: "openSourceShort", value: "Open Source | Gratuit" },
    { lang: "fr", key: "adminRequest", value: "[INFO] Demande de privileges Administrateur..." },
    { lang: "fr", key: "adminPrompt", value: "Veuillez cliquer sur Oui dans la fenetre UAC." },
    { lang: "fr", key: "adminError", value: "[ERREUR] Impossible d'obtenir les droits Administrateur." },
    { lang: "fr", key: "adminHint", value: "Veuillez faire un clic droit sur le script et selectionnez Executer avec PowerShell" },
    { lang: "fr", key: "pressAnyKey", value: "Appuyez sur une touche pour quitter..." },
    { lang: "fr", key: "restorePoint", value: "Creation d'un point de restauration systeme..." },
    { lang: "fr", key: "restoreSuccess", value: "Point de restauration cree avec succes." },
    { lang: "fr", key: "restoreFail", value: "Echec de la creation du point de restauration." },
    { lang: "fr", key: "complete", value: "OPTIMISATION TERMINEE" },
    { lang: "fr", key: "success", value: "Un redemarrage du systeme est recommande pour appliquer tous les changements." },
    { lang: "fr", key: "thankYou", value: "Merci d'utiliser OptWin !" },
    { lang: "fr", key: "author", value: "Developpe par ahmetly_" },
    { lang: "fr", key: "done", value: "Termine" },
    { lang: "fr", key: "developerName", value: "ahmetly" },
    { lang: "fr", key: "websiteUrl", value: "https://optwin.tech" },
    { lang: "fr", key: "githubUrl", value: "https://github.com/ahmetlygh/optwin" },
];
