export const defaultSettings = [
    { key: "maintenance_mode", value: "false", type: "boolean", description: "Site bakım modu" },
    { key: "site_version", value: "1.3.0", type: "string", description: "Görüntülenen sürüm" },
    { key: "github_url", value: "https://github.com/ahmetlygh/optwin", type: "string", description: "GitHub repo URL" },
    { key: "bmc_url", value: "https://www.buymeacoffee.com/ahmetly_", type: "string", description: "Buy Me a Coffee URL" },
    { key: "contact_email", value: "contact@optwin.tech", type: "string", description: "İletişim e-postası" },
    { key: "author_name", value: "ahmetly_", type: "string", description: "Geliştirici adı" },
    { key: "author_url", value: "https://ahmetly.com", type: "string", description: "Geliştirici web sitesi" },
    { key: "default_lang", value: "en", type: "string", description: "Varsayılan dil" },
    { key: "default_theme", value: "dark", type: "string", description: "Varsayılan tema" },
    { key: "script_format", value: "ps1", type: "string", description: "Script formatı" },
    { key: "bmc_widget_enabled", value: "true", type: "boolean", description: "BMC widget göster/gizle" },
    { key: "footer_year", value: "2025", type: "string", description: "Footer yıl metni" },
];

export const defaultDnsProviders = [
    { slug: "cloudflare", name: "Cloudflare", primary: "1.1.1.1", secondary: "1.0.0.1", order: 0 },
    { slug: "google", name: "Google", primary: "8.8.8.8", secondary: "8.8.4.4", order: 1 },
    { slug: "opendns", name: "OpenDNS", primary: "208.67.222.222", secondary: "208.67.220.220", order: 2 },
    { slug: "quad9", name: "Quad9", primary: "9.9.9.9", secondary: "149.112.112.112", order: 3 },
    { slug: "adguard", name: "AdGuard", primary: "94.140.14.14", secondary: "94.140.15.15", order: 4 },
];

export const defaultUiTranslations = [
    { key: "hero.title", en: "Optimize your Windows experience", tr: "Windows Deneyiminizi Hızlandırın" },
    { key: "hero.desc", en: "Select the optimizations you need and generate a custom script instantly.", tr: "İhtiyacınız olan optimizasyonları seçin ve anında sizin için bir script oluşturun." },
    { key: "btn.create", en: "Create Script", tr: "Script Oluştur" },
    { key: "footer.text", en: "Secure & Open Source.", tr: "Güvenli ve Açık Kaynak." },
    { key: "contact.message", en: "Feel free to email us for requests and suggestions.", tr: "İstek ve önerileriniz için mail atmaktan çekinmeyin." },
    { key: "nav.home", en: "Home", tr: "Ana Sayfa" },
    { key: "nav.about", en: "About", tr: "Hakkında" },
    { key: "search.placeholder", en: "Search features...", tr: "Özellik ara..." },
    { key: "search.noResults", en: "No features found", tr: "Özellik bulunamadı" },
    { key: "selected.count", en: "features selected", tr: "özellik seçildi" },
    { key: "risk.low", en: "Low Risk", tr: "Düşük Risk" },
    { key: "risk.medium", en: "Medium Risk", tr: "Orta Risk" },
    { key: "risk.high", en: "High Risk", tr: "Yüksek Risk" },
    { key: "preset.recommended", en: "Recommended Settings", tr: "Önerilen Ayarlar" },
    { key: "preset.gamer", en: "Gaming Settings", tr: "Oyuncu Ayarları" },
    { key: "preset.selectAll", en: "Select All", tr: "Hepsini Seç" },
    { key: "preset.reset", en: "Reset", tr: "Sıfırla" },
    { key: "about.title", en: "About OptWin", tr: "OptWin Hakkında" },
    { key: "about.subtitle", en: "Our mission is to empower Windows users with transparent, safe, and open-source optimization tools.", tr: "Misyonumuz, Windows kullanıcılarına şeffaf, güvenli ve açık kaynaklı optimizasyon araçları sağlamaktır." },
    { key: "about.safe.title", en: "Safe & Secure", tr: "Güvenli" },
    { key: "about.safe.desc", en: "Every optimization is carefully vetted. Your system's security is our priority.", tr: "Her optimizasyon dikkatle kontrol edilir. Sisteminizin güvenliği bizim önceliğimizdir." },
    { key: "about.open.title", en: "Open Source", tr: "Açık Kaynak" },
    { key: "about.open.desc", en: "Our code is transparent. Inspect, audit, and contribute on GitHub.", tr: "Kodumuz şeffaftır. GitHub'da inceleyebilir, denetleyebilir ve katkıda bulunabilirsiniz." },
    { key: "about.transparent.title", en: "Transparent", tr: "Şeffaf" },
    { key: "about.transparent.desc", en: "No hidden scripts. See exactly what your optimization does before running it.", tr: "Gizli scriptler yok. Optimizasyonun ne yaptığını çalıştırmadan önce tam olarak görün." },
    { key: "support.title", en: "Support OptWin Development", tr: "OptWin Gelişimini Destekleyin" },
    { key: "support.desc", en: "OptWin is 100% free and open-source. Your contribution helps keep it free for everyone.", tr: "OptWin %100 ücretsiz ve açık kaynaklıdır. Katkınız, OptWin'i herkes için ücretsiz tutmamıza yardımcı olur." },
    { key: "support.btn", en: "Buy Me a Coffee", tr: "Bana Kahve Al" },
    { key: "support.badgeFree", en: "100% Free", tr: "Ücretsiz" },
    { key: "support.badgeOpen", en: "Open Source", tr: "Açık Kaynak" },
    { key: "support.badgeSecure", en: "Secure", tr: "Güvenli" },
    { key: "dns.title", en: "DNS Configuration", tr: "DNS Yapılandırması" },
    { key: "dns.pingBtn", en: "Download Ping Test", tr: "Ping Testi İndir" },
    { key: "modal.restore.title", en: "System Restore Point", tr: "Sistem Geri Yükleme Noktası" },
    { key: "modal.restore.desc", en: "Do you want to add a System Restore Point creation step to the script? (Recommended)", tr: "Scripte geri yükleme noktası oluşturmayı eklemek ister misiniz? (Önerilir)" },
    { key: "modal.restore.yes", en: "Add", tr: "Ekle" },
    { key: "modal.restore.no", en: "No, Skip", tr: "Hayır, atla" },
    { key: "modal.warning.msg", en: "Please select at least one feature to generate a script.", tr: "Lütfen script oluşturmak için en az bir özellik seçin." },
    { key: "modal.warning.conflict", en: "You can only select one Power Plan (High or Ultimate).", tr: "Sadece bir Güç Planı seçebilirsiniz (Yüksek veya Nihai)." },
    { key: "overlay.title", en: "Script Preview", tr: "Script Önizleme" },
    { key: "overlay.badgeRun", en: "Can be run multiple times", tr: "Birden çok kez çalıştırılabilir" },
    { key: "overlay.badgeReady", en: "Ready for use", tr: "Kullanım için hazır" },
    { key: "overlay.download", en: "Download Script", tr: "Script İndir" },
    { key: "overlay.close", en: "Close", tr: "Kapat" },
    { key: "overlay.copy", en: "Copy", tr: "Kopyala" },
    { key: "overlay.copied", en: "Copied!", tr: "Kopyalandı!" },
];
